/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.Department;
import Logic.Employee;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Name: AddDepartmentForm
 * Purpose: This is a Java Swing GUI class that provides a form for adding new
 * departments to the system. It interacts with the main application window to
 * update department data and GUI components.
 *
 * @author Zainab
 * @version 1.0
 */
public class AddDepartmentForm extends javax.swing.JFrame {

    MainWindow main;//Purpose: Reference to the main application window to access shared data and methods.
    ArrayList<Department> departments;//Purpose: List of departments fetched from the main window.
    ArrayList<Employee> allEmployees;//Purpose: List of employees fetched from the main window.

    /**
     * Name: AddDepartmentForm
     *
     * Default constructor for AddDepartmentForm.
     *
     * Purpose: Initializes the form components but does NOT set 'main' or load
     * data. Input: none Output: none Effect: Creates the form window but it is
     * not linked to main data yet.
     */
    public AddDepartmentForm() {
        initComponents();
    }

    /**
     * Name: AddDepartmentForm
     *
     * Parameterized constructor to initialize AddDepartmentForm with reference
     * to main window.
     *
     * @param main The main application window object to access shared data.
     *
     * Purpose: To create the form and properly link it to the main application
     * data. Input: MainWindow object to get department and employee data.
     * Output: none Effect: Initializes components, sets 'main', and centers
     * form on screen.
     */
    public AddDepartmentForm(MainWindow main) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.main = main;
        this.departments = main.departments;
        this.allEmployees = main.allEmployees;

        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);

        this.setLocation(x, y);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        departmentNameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        cancelButton2 = new javax.swing.JButton();
        addDepartmentConfirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Department Name");

        departmentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentNameFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Location");

        locationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFieldActionPerformed(evt);
            }
        });

        cancelButton2.setText("Cancel");
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });

        addDepartmentConfirmButton.setText("Add Department");
        addDepartmentConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartmentConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addDepartmentConfirmButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addComponent(departmentNameField)
                        .addComponent(jLabel10)
                        .addComponent(locationField, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton2)
                    .addComponent(addDepartmentConfirmButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Name: departmentNameFieldActionPerformed
     *
     * Event handler for the departmentNameField action event.
     *
     * @param evt The action event triggered by user input.
     *
     * Purpose: Placeholder for handling action on the department name text
     * field. Input: Action event Output: none Effect: Currently does nothing.
     */
    private void departmentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentNameFieldActionPerformed
    /**
     * Name: locationFieldActionPerformed
     *
     * Event handler for the locationField action event.
     *
     * @param evt The action event triggered by user input.
     *
     * Purpose: Placeholder for handling action on the location text field.
     * Input: Action event Output: none Effect: Currently does nothing.
     */
    private void locationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationFieldActionPerformed
    /**
     * Name: cancelButton2ActionPerformed
     *
     * Event handler for the Cancel button.
     *
     * @param evt The action event triggered by clicking Cancel.
     *
     * Purpose: To close the AddDepartmentForm and return to the main window.
     * Input: Action event Output: none Effect: Makes main window visible and
     * disposes this form.
     */
    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton2ActionPerformed
        // TODO add your handling code here:
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelButton2ActionPerformed
    /**
     * Name: addDepartmentConfirmButtonActionPerformed
     *
     * Event handler for the Add Department confirmation button.
     *
     * @param evt The action event triggered by clicking Add Department.
     *
     * Purpose: Validates input, creates a new Department, adds it to the main
     * list, updates GUI components, and closes the form. Input: Action event
     * Output: none Effect: Updates main window department data and UI, shows
     * error dialogs if needed.
     */
    private void addDepartmentConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartmentConfirmButtonActionPerformed
        try {
            String departmentName = departmentNameField.getText().trim();
            String location = locationField.getText().trim();

            // Validate input
            if (departmentName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Department name cannot be empty.", "Input Error", JOptionPane.WARNING_MESSAGE);
                departmentNameField.requestFocus();
                return;
            }
            
            //Validate input is only strings
            if (!departmentName.matches("[a-zA-Z]+")) {
                JOptionPane.showMessageDialog(this, "Please enter only letters.", "Input Error", JOptionPane.WARNING_MESSAGE);
                departmentNameField.requestFocus();
                return;
            } 

            if (location.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Location cannot be empty.", "Input Error", JOptionPane.WARNING_MESSAGE);
                locationField.requestFocus();
                return;
            }
            
            //Validate input is only strings
            if (!location.matches("[a-zA-Z]+")) {
                JOptionPane.showMessageDialog(this, "Please enter only letters.", "Input Error", JOptionPane.WARNING_MESSAGE);
                locationField.requestFocus();
                return;
            } 

            // Create new department without assigning a head
            main.staticDeptID++;
            Department newDepartment = new Department(main.staticDeptID, departmentName, location);

            // Add to departments list
            departments.add(newDepartment);

            // Update departments table
            main.refreshDepartmentTable();

            // Clear form fields
            departmentNameField.setText("");
            locationField.setText("");

            // Refresh combo box and close the form
            main.populateDepartmentsComboBox();
            main.refreshDepartmentsComboBox();
            main.setVisible(true);
            this.dispose();

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this,
                    "An unexpected error occurred: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "An error occurred while creating the department: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }

    }//GEN-LAST:event_addDepartmentConfirmButtonActionPerformed

    /**
     * /
     *
     **
     * @param args the command line arguments Name: main
     *
     * Main method to run the AddDepartmentForm standalone for testing.
     *
     * @param args Command line arguments .
     *
     * Purpose: Launches the form UI. Input: Command line arguments. Output:
     * none Effect: Creates and displays the AddDepartmentForm window.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDepartmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDepartmentConfirmButton;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JTextField departmentNameField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField locationField;
    // End of variables declaration//GEN-END:variables
}
